#pragma once

/* Minimal single-page config/status UI, kept intentionally small to fit in flash. */
static const char INDEX_HTML[] =
"<!DOCTYPE html><html><head><meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>Fan Controller</title>"
"<style>body{font-family:sans-serif;max-width:480px;margin:1em auto;padding:0 1em}"
"fieldset{margin-bottom:1em}label{display:block;margin:.4em 0 .1em}"
"input,select{width:100%;box-sizing:border-box;padding:.4em}"
"button{padding:.6em 1em;margin-top:.6em}</style></head><body>"
"<h2>Radiator Fan Controller</h2>"
"<fieldset><legend>Status</legend>"
"<div>NTC1: <span id='t1'>--</span> &deg;C</div>"
"<div>NTC2: <span id='t2'>--</span> &deg;C</div>"
"<div>Fan duty: <span id='fan'>--</span> %</div>"
"</fieldset>"
"<fieldset><legend>Wi-Fi (STA)</legend>"
"<label>SSID</label><input id='sta_ssid'>"
"<label>Password</label><input id='sta_pass' type='password'>"
"</fieldset>"
"<fieldset><legend>MQTT</legend>"
"<label>Broker URI (mqtt://host:1883)</label><input id='mqtt_uri'>"
"<label>User</label><input id='mqtt_user'>"
"<label>Password</label><input id='mqtt_pass' type='password'>"
"</fieldset>"
"<fieldset><legend>Wireless Features</legend>"
"<label><input type='checkbox' id='zb_en' style='width:auto'> Zigbee</label>"
"<label><input type='checkbox' id='th_en' style='width:auto'> Thread</label>"
"<label><input type='checkbox' id='en_en' style='width:auto'> ESP-NOW</label>"
"</fieldset>"
"<fieldset><legend>OTA</legend>"
"<label>Firmware URL</label><input id='ota_url'>"
"<button onclick='doOta()'>Update from URL</button>"
"</fieldset>"
"<button onclick='saveCfg()'>Save Settings</button>"
"<script>"
"async function loadStatus(){const r=await fetch('/api/status');const j=await r.json();"
"document.getElementById('t1').textContent=j.ntc1_c.toFixed(1);"
"document.getElementById('t2').textContent=j.ntc2_c.toFixed(1);"
"document.getElementById('fan').textContent=j.fan_pct;}"
"async function loadCfg(){const r=await fetch('/api/config');const j=await r.json();"
"for(const k in j){const el=document.getElementById(k);if(!el)continue;"
"if(el.type==='checkbox')el.checked=!!j[k];else el.value=j[k];}}"
"async function saveCfg(){const ids=['sta_ssid','sta_pass','mqtt_uri','mqtt_user','mqtt_pass','ota_url'];"
"const body={};ids.forEach(id=>body[id]=document.getElementById(id).value);"
"['zb_en','th_en','en_en'].forEach(id=>body[id]=document.getElementById(id).checked);"
"await fetch('/api/config',{method:'POST',body:JSON.stringify(body)});alert('Saved. Rebooting...');}"
"async function doOta(){const url=document.getElementById('ota_url').value;"
"await fetch('/api/ota',{method:'POST',body:JSON.stringify({url})});alert('OTA started');}"
"loadStatus();loadCfg();setInterval(loadStatus,3000);"
"</script></body></html>";
